<?= '<?xml version="1.0" encoding="UTF-8" ?>' ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>http://jlamartistry.com/</loc>
      <lastmod>2014-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.6</priority>
   </url>
   <url>
      <loc>http://jlamartistry.com/lifestyle</loc>
      <lastmod>2014-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.6</priority>
   </url>
   <url>
      <loc>http://jlamartistry.com/fashion</loc>
      <lastmod>2014-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.6</priority>
   </url>
   <url>
      <loc>http://jlamartistry.com/celebrity</loc>
      <lastmod>2014-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.6</priority>
   </url>
   <url>
      <loc>http://jlamartistry.com/bridal</loc>
      <lastmod>2014-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.6</priority>
   </url>
   <url>
      <loc>http://jlamartistry.com/bio</loc>
      <lastmod>2014-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>.9</priority>
   </url>
   <url>
      <loc>http://jlamartistry.com/services</loc>
      <lastmod>2014-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>http://jlamartistry.com/contact</loc>
      <lastmod>2014-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.7</priority>
   </url>
</urlset>
